### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by kiirtaxh** [Regigicas/Launcher-GPLP-qt#1]
- [ ] Detectar rutas de instalación del cliente y modificar el realmlist.
- [ ] Soporte para 3.3.5a y 4.3.4 (barra izquierda) y localhost (desplegable) de ambos. 
- [ ] Menú de opciones con repair, selección de rutas, modificación de la configuración de juego y link a las webs.
- [ ] Autoactualizador del launcher.
- [ ] Instalador del cliente on demand de cataclysm. Sería bueno que calculase el porcentaje de descarga que le queda para completarse.
- [ ] Changelogs de emu y DB mediante consultas a git/svn.
- [ ] Consulta de noticias a la web.
